version: '3.8'
services:
  # web:
  #   container_name: nginx
  #   image: tempest_nginx_image
  #   build: .
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./oneofone-location.conf:/etc/nginx/oneofone-location.conf
  #     - ./mime.types:/etc/nginx/mime.types
  #     - ./entrypoint.sh:/entrypoint.sh
  #     - ./resource:/home/resource
  #     - ./localhost.pem:/etc/nginx/localhost.pem
  #     - ./localhost-key.pem:/etc/nginx/localhost-key.pem
  #   command: "/entrypoint.sh"
  #   networks:
  #     - bespokenetwork 

  database:
    container_name: gimbapdb
    image: mariadb:10.8.3
    ports:
      - "3306:3306"
      
    environment:
      MYSQL_ROOT_PASSWORD: zaq12wsx
      MYSQL_DATABASE: gimbap_db
      MYSQL_USER: gimbap_user
      MYSQL_PASSWORD: zaq12wsx
    volumes:
      - ./database:/var/lib/mysql
      # - ./config:/etc/mysql/conf.d
      # - ./mariadb_data:/var/lib/mysql
      # - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - gimbapnetwork 

  application:
    container_name: gimbap_backend
    image: ghcr.io/eddykimm/gimbap/gimbap_backend:latest
    ports:
      - "8080:8080"
    # environment:
    #   - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - database
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - gimbapnetwork

networks:
  gimbapnetwork:
    driver: bridge